pipeline {
    agent any
    stages { 
        stage('Checkout') {
            steps {
                echo 'pull git'
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'af677054-adff-4722-a295-c2516fcb8b7e', url: 'https://github.com/Junweiding/stock-market-chart-springcloud-master.git']]])
            }
        } 
        stage('Package') {
            steps {
                echo 'package'
                bat "mvn -Dmaven.test.failure.ignore clean package" 
            }
        }
        stage('Build') { 
            steps { 
                echo "Build To Docker!" 
                bat 'docker build -t eureka:v1 .' 
            } 
        }    
        stage('Run') { 
            steps { 
                echo "Run Docker Image" 
                bat 'docker run -d -p 9100:9100 eureka:v1' 
            } 
        }     
    }
}